config/routes.rb
Eenge::Application.routes.draw do
  
  resources :album_de_fotos
  
  resources :fotos
  
  devise_for :users

  resources :inscricaos, :only => [:new, :create, :update, :edit]
  
  resources :users do
    post 'confirmar', :on => :member
    post 'desfazer', :on => :member
  end
  
  resources :contatos, :only => [:new, :create]
  
  root :to => 'pages#home'
  
  match '/patrocinio', :to => 'pages#sponsors', :via => :get
  match '/sobre', :to => 'pages#sobre', :via => :get
  match '/programacao', :to => 'pages#programacao', :via => :get
  match '/usuario', :to => 'users#show', :via => :get
  match '/localizacao', :to => 'pages#localizacao', :via => :get
  match '/contato', :to => 'pages#contato', :via => :get
  match '/cronograma', :to => 'pages#cronograma', :via => :get
  match '/minicursos', :to => 'pages#minicursos', :via => :get
  match '/coquetel', :to => 'pages#coquetel', :via => :get
  match '/visitas_tecnicas', :to => 'pages#visitas_tecnicas', :via => :get
  match '/como_chegar', :to => 'pages#como_chegar', :via => :get
  match '/aonde_ficar', :to => 'pages#aonde_ficar', :via => :get
  match '/ficha_cadastral', :to => 'users#ficha', :via => :get
  match '/pagamento', :to => 'pages#pagamento', :via => :get
  match '/congresso_pmi', :to => 'pages#congresso_pmi', :via => :get
  match '/efetuado', :to => 'pages#efetuado'  
  
  namespace :user do
    root :to => 'users#show'
  end
  
  resources :noticias, :except => [:index]
  resources :patrocinadores
    

end

app/models/album_de_foto.rb
class AlbumDeFoto < ActiveRecord::Base
  has_many :fotos
  
  validates :nome, :presence => true
end

app/controllers/album_de_fotos_controller.rb
class AlbumDeFotosController < ApplicationController
  def index
    @album_de_fotos = AlbumDeFoto.all
  end

  def show
    @album_de_foto = AlbumDeFoto.find(params[:id])
  end

  def new
    @album_de_foto = AlbumDeFoto.new
  end

  def edit
    @album_de_foto = AlbumDeFoto.find(params[:id])
  end

  def create
    @album_de_foto = AlbumDeFoto.new(params[:album_de_foto])

    if @album_de_foto.save
      redirect_to album_de_fotos_path
    else
      render :action => "new"
    end
  end

  def update
    @album_de_foto = AlbumDeFoto.find(params[:id])

    if @album_de_foto.update_attributes(params[:album_de_foto])
      redirect_to album_de_fotos_path
    else
      render :action => "edit"
    end
  end

  def destroy
    @album_de_foto = AlbumDeFoto.find(params[:id])
    @album_de_foto.destroy

    redirect_to(album_de_fotos_url)
  end
end

app/views/album_de_fotos/_form.html.erb
<div class="form_item">
	<div class="body">
		<%= form_for @album_de_foto, :html => {:multipart => true} do |f| %>
		
			<p><%= f.label :nome %><br />
				<%= f.text_field :nome %></p>

  	    	<%= f.submit "Criar" %>
		<% end %>
	</div>
</div>

app/views/album_de_fotos/edit.html.erb
<h1>Renomear album</h1>

<%= render 'form' %>

<%= link_to 'voltar', album_de_fotos_path %>

app/views/album_de_fotos/index.html.erb
<div class="item">
	<div class="title"><small>12º EENGE</small> <span class="azul">Fotos</span></div>	

		<% @album_de_fotos.each do |album_de_foto| %>

			<div class="body">
				<div class="titulo_imagem center"><%= album_de_foto.nome %></div>
				<br />
				<br />
				<% album_de_foto.fotos.each do |foto| %>
					<div class="imagem">
						<%= link_to image_tag(foto.pic.url, :size => '130x80'), foto, :class => "patrocinador"  %>						
					<br />
					
					<% if current_user.try(:admin) %>
						<%= link_to "apagar", foto, :method => :delete, :confirm => 'Deseja realmente apagar?'%>
					<% end %>							
					</div>
				<% end %>

				<% if current_user.try(:admin) %>
				<div class="center">
				  <tr>
 
					<td><%= link_to 'renomear', edit_album_de_foto_path(album_de_foto) %></td> |
				   <td><%= link_to 'apagar álbum', album_de_foto, :confirm => 'Deseja realmente apagar?', :method => :delete %></td>
				  </tr>
				</div>
				<% end %>
			</div>
		<% end %>


		<div class="body">
		<% if current_user.try(:admin) %>
			<%= link_to 'Novo Álbum', new_album_de_foto_path %> 
			<% if AlbumDeFoto.all.length > 0 %>
			| <%= link_to 'Nova Foto', new_foto_path %>
			<% end %>
		<% end %>
		</div>
</div>

app/views/album_de_fotos/new.html.erb
<h1>Novo Album</h1>

<%= render 'form' %>

<%= link_to 'Back', album_de_fotos_path %>