config/routes.rb
Eenge::Application.routes.draw do
  
  resources :album_de_fotos
  
  resources :fotos
  
  devise_for :users

  resources :inscricaos, :only => [:new, :create, :update, :edit]
  
  resources :users do
    post 'confirmar', :on => :member
    post 'desfazer', :on => :member
  end
  
  resources :contatos, :only => [:new, :create]
  
  root :to => 'pages#home'
  
  match '/patrocinio', :to => 'pages#sponsors', :via => :get
  match '/sobre', :to => 'pages#sobre', :via => :get
  match '/programacao', :to => 'pages#programacao', :via => :get
  match '/usuario', :to => 'users#show', :via => :get
  match '/localizacao', :to => 'pages#localizacao', :via => :get
  match '/contato', :to => 'pages#contato', :via => :get
  match '/cronograma', :to => 'pages#cronograma', :via => :get
  match '/minicursos', :to => 'pages#minicursos', :via => :get
  match '/coquetel', :to => 'pages#coquetel', :via => :get
  match '/visitas_tecnicas', :to => 'pages#visitas_tecnicas', :via => :get
  match '/como_chegar', :to => 'pages#como_chegar', :via => :get
  match '/aonde_ficar', :to => 'pages#aonde_ficar', :via => :get
  match '/ficha_cadastral', :to => 'users#ficha', :via => :get
  match '/pagamento', :to => 'pages#pagamento', :via => :get
  match '/congresso_pmi', :to => 'pages#congresso_pmi', :via => :get
  match '/efetuado', :to => 'pages#efetuado'  
  
  namespace :user do
    root :to => 'users#show'
  end
  
  resources :noticias, :except => [:index]
  resources :patrocinadores
    

end

app/models/user.rb
#coding: utf-8

class User < ActiveRecord::Base
  after_create :send_email
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :instituicao, :tipo_inscricao, :nome, :sexo, :data_nascimento, :cpf, 
                  :logradouro, :bairro, :cidade, :estado, :cep, :telefone, 
                  :email, :password, :password_confirmation, :remember_me, :status_inscricao
                  
  validates :nome, :sexo, :data_nascimento, :cpf, :logradouro, :bairro, 
            :cidade, :estado, :cep, :telefone, :tipo_inscricao, :presence => true
            
  validates :cpf, :uniqueness => true
  
  validates_presence_of :instituicao, :if => :nao_uenf?

  
  usar_como_cpf :cpf
  
  has_many :eventos
  
  def primeiro_nome
    nome.split(' ').first
  end
  
  def sobrenome
    nome.split(' ').last
  end
  
  def numero_inscricao
    498 + id
  end

  def preco_inscricao
    tipo_inscricao.split("R$").second
  end
  
  def tipo_da_inscricao
    tipo_inscricao.split("R$").first
  end
  
  def confirmado?
    status_inscricao == "Confirmada"
  end
  
  def inscricao_pagavel?
    (["Confirmada", "Aguardando confirmação do pagamento no PagSeguro", "Pagamento em analise pelo PagSeguro"].include? status_inscricao) ? false : true    
  end

  def estudante_uenf?
    tipo_da_inscricao == "Estudante UENF "    
  end
  
  def nao_uenf?
    tipo_da_inscricao != "Estudante UENF "
  end
  
  def voluntario_pmi?
    tipo_da_inscricao == "Voluntário PMI "
  end
  
  def estudante_externo?
    tipo_da_inscricao == "Estudante Externo "
  end
  
  def outros?
    tipo_da_inscricao == "Outros "
  end

  def send_email
    Notifier.inscricao_criada(self).deliver
  end
  
end

app/controllers/users_controller.rb
#coding: utf-8

class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    redirect_to root_path    if current_user.try(:admin)
  end
  
  def index
    redirect_to root_path if !current_user.try(:admin) 
    @users = User.find_all_by_admin("false", :order => "created_at")
    
    @users_confirmados = @users.select {|user| user.status_inscricao == "Confirmada" }
    @users_pendentes = @users.select {|user| user.status_inscricao != "Confirmada" }

    respond_to do |format|
      format.html { render :layout => "index" }
      format.xls { send_data @users.to_xls}
    end
  end
  
  def dados
  end
  
  def ficha
    if current_user.status_inscricao != "Confirmada"
      redirect_to root_path 
    else
      render :layout => 'ficha'      
    end

  end
  
  def confirmar
    @user = User.find(params[:id])
    @user.status_inscricao = "Confirmada"
    
    if @user.save
      Notifier.confirmacao(@user).deliver
      redirect_to users_path
    else
      redirect_to users_path, :notice => "Algo deu errado"  
    end
  end
  
  def desfazer
    @user = User.find(params[:id])
    @user.status_inscricao = "Aguardando Pagamento"
    
    if @user.save
      Notifier.cancelamento(@user).deliver      
      redirect_to users_path
    else
      redirect_to users_path, :notice => "Algo deu errado"  
    end
  end   
  
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])    

    if @user.update_attributes(params[:user])
      redirect_to(users_path, :notice => 'User editado com sucesso.')
    else
      render :action => "edit"
    end
  end  
end

app/views/users/_user.html.erb
<tr onclick="window.location = '<%= edit_user_path(user) %>'">
	<td><%= link_to "pagou", confirmar_user_path(user), :method => :post %></td>			
	<td><%= "#{@users.index(user) + 501}" %></td>
	<td><strong><%= user.nome %></strong></td>
	<td><%= user.cpf %></td>
	<td><%= user.email %></td>
	<td><%= user.telefone %></td>
	<td><%= user.tipo_da_inscricao %></td>						
	<td><%= user.instituicao %></td>
	<td><%= link_to "editar", edit_user_path(user) %></td>
</tr>

app/views/users/edit.html.erb
<% if current_user.try(:admin) %>

	<%= form_for(@user, :action => "atualizar", :method => :post) do |f| %>				

	<div class="form_item">
		<h3>Inscrição</h3>	

		<div class="body">
			<p><%= f.label :tipo_inscricao, "Tipo de Inscrição" %><br />
			<%= f.select :tipo_inscricao, tipos_de_inscricao, :id => "mySelect" %></p>

			<p id="instituicao"><%= f.label :instituicao, "Instituição/ Universidade" %>
			<%= f.text_field :instituicao %><br /></p>

		</div>
	</div>


	<div class="form_item">
		<div class="title">
			<h3>Dados Pessoais</h3>	
		</div>

		<div class="body">
			<p><%= f.label :nome %><br />
			<%= f.text_field :nome %></p>

			<p><%= f.label :sexo %><br />
			<%= f.select :sexo, ["Masculino", "Feminino"], :include_blank => true %></p>

			<p><%= f.label :data_nascimento %><br />
			<%= f.date_select :data_nascimento, :start_year => 2000, :end_year => 1900, :include_blank => true,  
							:order => [:day, :month, :year], :use_month_numbers => true %></p>

			<p><%= f.label :cpf, "CPF" %>
			<%= f.text_field :cpf, :onkeypress => "formatar('###.###.###-##', this)", 
											:maxlength => "14", :size => '16' %></p>

			<p><%= f.label :logradouro %><br />
			<%= f.text_field :logradouro %></p>

			<p><%= f.label :bairro %><br />
			<%= f.text_field :bairro %></p>

			<p><%= f.label :cidade %><br />
			<%= f.text_field :cidade %></p>

			<p><%= f.label :estado, "Estado (UF)" %><br />
			<%= f.select :estado, estados, :include_blank => true %></p>


			<p><%= f.label :cep, "CEP" %>
			<%= f.text_field :cep, :onkeypress => "formatar('#####-###', this)",
			 							  :maxlength => "9", :size => "10"%></p>

			<p><%= f.label :telefone %>
			<%= f.text_field :telefone, :onkeypress => "formatar('## ####-####', this)", 
												 :maxlength => "12", :size => "13" %></p>
		</div>
	</div>


  <p><%= f.submit "Atualizar dados" %></p>		
	<% end %>
<% end %>

app/views/users/ficha.html.erb
<div id="ficha_cadastral">
	<table>
		<tr class="logo">
			<td><%= image_tag('/images/EengeSmall.gif', :size => '160x50') %> <span><%= curso %></span></td>
			<td><span>Inscrição nº:</span> <%= current_user.numero_inscricao %></td>
		</tr>

				<tr class="space"></tr>

		<tr>
			<td class="subtitulo">Dados Pessoais</td>
		</tr>

				<tr class="space"></tr>

		<tr>
			<td><span>Nome:</span> <%= current_user.nome %></td>
			<td><span>Data de Nascimento:</span> <%= current_user.data_nascimento.strftime("%d/%m/%Y") %></td>
		</tr>
		
		<tr>
			<td><span>CPF:</span> <%= current_user.cpf %></td>
			<td><span>Sexo:</span> <%= current_user.sexo %></td>						
		</tr>

		<tr>

		</tr>

				<tr class="space"></tr>

		<tr>
			<td class="subtitulo">Endereço</td>
		</tr>

				<tr class="space"></tr>

		<tr>
			<td><%= "#{current_user.logradouro} - #{current_user.bairro} - #{current_user.cidade}/#{current_user.estado} #{current_user.cep}" %></td>
		</tr>

				<tr class="space"></tr>
	
		<tr>
			<td class="subtitulo">Tipo da Inscrição</td>
		</tr>

				<tr class="space"></tr>			

		<tr>
			<td><span><%= "#{current_user.tipo_da_inscricao} - #{current_user.instituicao}"%> </span></td>
		</tr>

				<tr class="space"></tr>

	</table>
</div>

app/views/users/index.html.erb
<div class="item">
	<!-- <div class="body excel">
		<%= link_to "Arquivo Excel", "/users.xls" %>
	</div> -->
	
	<h3>Inscrições Pendentes</h3>
	<div class="body">
		<% if @users_pendentes %>
				
				<table class="user_item">
					<tr>
						<th></th>
						<th>N.</th>
						<th class="large">Nome</th>
						<th class="medium">CPF</th>
						<th class="medium">Email</th>
						<th class="medium">Telefone</th>
						<th class="medium">Tipo da Inscrição</th>
						<th class="medium">Instituição</th>
					</tr>
					
						<% @users_pendentes.each do |user| %>
						<tr onclick="window.location = '<%= edit_user_path(user) %>'">
						<td><%= link_to "pagou", confirmar_user_path(user), :method => :post %></td>			
						<td><%= "#{@users.index(user) + 501}" %></td>
						<td><strong><%= user.nome.gsub(/\.+/) {|word| word.capitalize} %></strong></td>
						<td><%= user.cpf %></td>
						<td><%= user.email %></td>
						<td><%= user.telefone %></td>
						<td><%= user.tipo_da_inscricao %></td>						
						<td><%= user.instituicao %></td>
						<td><%= link_to "editar", edit_user_path(user) %></td>
						</tr>
						<% end %>
				</table>
				
		<% end %>		
		<b>Pendentes:</b> <%= @users_pendentes.count %><br />
	</div>
	
	
	<h3>Confirmadas</h3>
	<div class="body">
		<% if @users_confirmados %>
				
				<table class="user_item">
					<tr>
						<th></th>
						<th>N.</th>
						<th class="large">Nome</th>
						<th class="medium">CPF</th>
						<th class="medium">Email</th>
						<th class="medium">Telefone</th>
						<th class="medium">Tipo da Inscrição</th>
						<th class="medium">Instituição</th>
					</tr>
					
						<% @users_confirmados.each do |user| %>
						<tr onclick="window.location = '<%= edit_user_path(user) %>'">
						<td><%= link_to "editar", edit_user_path(user) %></td>							
						<td><%= "#{@users.index(user) + 501}" %></td>
						<td><strong><%= user.nome.gsub(/\w+/) {|word| word.capitalize!} %></strong></td>
						<td><%= user.cpf %></td>
						<td><%= user.email %></td>
						<td><%= user.telefone %></td>						
						<td><%= user.tipo_da_inscricao %></td>						
						<td><%= user.instituicao %></td>

						<td><%= link_to "cancelar", desfazer_user_path(user), :method => :post, :confirm => "Deseja cancelar inscrição do usuário?" %></td>
						</tr>
						<% end %>
				</table>
				
		<% end %>		
		<b>Confirmados:</b> <%= @users_confirmados.count %><br /><br />
	</div>
	

</div>

app/views/users/show.html.erb
<div class="item">
	<h3>Inscrição</h3>
	<div class="body">	
		<br />
		<div class="situacao"><%= current_user.status_inscricao %></div>
		<% if current_user.status_inscricao == "Confirmada" %><br />
			Imprima sua <%= link_to "ficha cadastral", ficha_cadastral_path %>
		<% end %>
		
	</div>

	<% if current_user.inscricao_pagavel? %>
	<h3>Dados</h3>
	<div class="body">
		<table class="dados_usuario">
			<tr>
				<td class="left"><strong>Nome:</strong></td> 
				<td> <%= current_user.nome %></td>
			</tr>
			
			<tr>
				<td class="left"><strong>Data Nascimento:</strong></td> 
				<td> <%= current_user.data_nascimento.strftime("%d/%m/%Y") %></td>
			</tr>
			
			<tr>
				<td class="left"><strong>CPF:</strong> </td> 
				<td><%= current_user.cpf %></td>		
			</tr>
			
			<tr>
				<td class="left"><strong>Inscrição nº:</strong></td> 
				<td><%= current_user.numero_inscricao %></td>				
			</tr>
			
			<tr>
				<td class="left"><strong>Tipo:</strong></td> 
				<% if current_user.estudante_uenf? %>
					<td> <%= "#{current_user.tipo_da_inscricao}" %></td>				
				<% else %>
					<td> <%= "#{current_user.tipo_da_inscricao} - #{current_user.instituicao}" %></td>
				<% end %>
			</tr>
			
			<tr>
				<td class="left"><strong>Tel.:</strong></td>
				<td><%= current_user.telefone %></td>
			</tr>
			
			<tr>
				<td class="left"><strong>Endereço:</strong></td> 
				<td><%= "#{current_user.logradouro} - #{current_user.bairro} - #{current_user.cidade}/#{current_user.estado} #{current_user.cep}" %></td>
			</tr>
			
			<tr>
				<td></td>
				<td><%= button_to "editar", edit_registration_path(current_user), :method => "get" %></td>
			</tr>

		</table>	
	</div>
	

	

		<h2>Pagar</h2>
		<div class="body">
			<table class="total">
				<tr>
					<td class="nome">Total:</td>
					<td class="preco">1 Inscrição <%= current_user.tipo_inscricao %> </td>
				</tr>
			</table>
			
			<div class="formas_pagamento">
				
				<div class="item">
				<p><strong>PagSeguro</strong>: Você protege seus dados financeiros (não informa os seus dados para o vendedor), o pagamento é seguro (você tem 14 dias para bloquear o pagamento) e paga como quiser (boleto ou tranferência eletrônica). Para isso você precisará fazer um breve cadastro no PagSeguro, caso não o tenha é possível fazê-lo na hora da compra.</p>

				<div class="center">
					<% if current_user.estudante_uenf? %>
						<form target="pagseguro" action="https://pagseguro.uol.com.br/v2/checkout/payment.html" method="post">
						<input type="hidden" name="code" value="FBE8E17EEDED74DAA4CF6FA4FDA32455" />
						<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/120x53-pagar-preto.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
						</form>
					<% elsif current_user.voluntario_pmi? %>
						<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
						<form target="pagseguro" action="https://pagseguro.uol.com.br/v2/checkout/payment.html" method="post">
						<input type="hidden" name="code" value="CCD0D1F91010B3C77498BFA61B1FE20C" />
						<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/120x53-pagar-preto.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
						</form>
						<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
					<% elsif current_user.estudante_externo? %>
						<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
						<form target="pagseguro" action="https://pagseguro.uol.com.br/v2/checkout/payment.html" method="post">
						<input type="hidden" name="code" value="0D679438A9A995CDD45A1F81E977AFAE" />
						<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/120x53-pagar-preto.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
						</form>
						<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
					<% elsif current_user.outros? %>
					 	<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
						<form target="pagseguro" action="https://pagseguro.uol.com.br/v2/checkout/payment.html" method="post">
						<input type="hidden" name="code" value="82FF2C06BDBD145EE40C9FBAB35CD3E1" />
						<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/120x53-pagar-preto.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
						</form>
						<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
					<% end %>
				</div>
								
				</div>
								
			</div>
		</div>
	<% end %>
</div>