config/routes.rb
Eenge::Application.routes.draw do
  
  resources :album_de_fotos
  
  resources :fotos
  
  devise_for :users

  resources :inscricaos, :only => [:new, :create, :update, :edit]
  
  resources :users do
    post 'confirmar', :on => :member
    post 'desfazer', :on => :member
  end
  
  resources :contatos, :only => [:new, :create]
  
  root :to => 'pages#home'
  
  match '/patrocinio', :to => 'pages#sponsors', :via => :get
  match '/sobre', :to => 'pages#sobre', :via => :get
  match '/programacao', :to => 'pages#programacao', :via => :get
  match '/usuario', :to => 'users#show', :via => :get
  match '/localizacao', :to => 'pages#localizacao', :via => :get
  match '/contato', :to => 'pages#contato', :via => :get
  match '/cronograma', :to => 'pages#cronograma', :via => :get
  match '/minicursos', :to => 'pages#minicursos', :via => :get
  match '/coquetel', :to => 'pages#coquetel', :via => :get
  match '/visitas_tecnicas', :to => 'pages#visitas_tecnicas', :via => :get
  match '/como_chegar', :to => 'pages#como_chegar', :via => :get
  match '/aonde_ficar', :to => 'pages#aonde_ficar', :via => :get
  match '/ficha_cadastral', :to => 'users#ficha', :via => :get
  match '/pagamento', :to => 'pages#pagamento', :via => :get
  match '/congresso_pmi', :to => 'pages#congresso_pmi', :via => :get
  match '/efetuado', :to => 'pages#efetuado'  
  
  namespace :user do
    root :to => 'users#show'
  end
  
  resources :noticias, :except => [:index]
  resources :patrocinadores
    

end

app/views/pages/como_chegar.html.erb
<div class="item">
	<div class="title"><small>12º EENGE</small> <span class="azul"><%= @titulo %></span></div>
	
	<div class="body">
		
				
		<% if @noticia %>
			<%= raw RedCloth.new(@noticia.corpo).to_html %>
			<% if current_user.try(:admin) %>			
			  <%= link_to "Editar informações", edit_noticia_path(@noticia) %>
			<% end %>
		<% else %>
			<% if current_user.try(:admin) %>
			  <%= link_to "Inserir informações", new_noticia_path(:secao => @secao) %>
			<% end %>
		<% end %>
		
		
	</div>
	

</div>

app/views/pages/efetuado.html.erb
<div class="item">
	<div class="body">
			<h3>Pedido efetuado com sucesso!</h3>
			
 		<p>Sua inscrição estará completa assim que verificarmos a confirmação do seu pagamento junto ao <strong>PagSeguro</strong>. Acompanhe o andamento da sua inscrição <%= link_to "aqui", usuario_path %>.</p>
		<strong>Bom Evento!</strong>
	</div>
</div>

app/views/pages/home.html.erb
<div class="item">

	<div class="principal">
		<% if @noticia_principal.present? %>
			<!-- AddThis Button BEGIN -->
			<div class="addthis_toolbox addthis_default_style ">
			<a class="addthis_button_preferred_1"></a>
			<a class="addthis_button_preferred_2"></a>
			<a class="addthis_button_preferred_3"></a>
			<a class="addthis_button_preferred_4"></a>
			<a class="addthis_button_compact"></a>
			<a class="addthis_counter addthis_bubble_style"></a>
			</div>
			<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4ea5f86c1a1b04d9"></script>
			<br />
		<!-- AddThis Button END -->
		
			<%= raw RedCloth.new(@noticia_principal.corpo).to_html %>
			<% if current_user.try(:admin) %>
				<%= link_to "editar", edit_noticia_path(@noticia_principal) %>
			<% end %>
		<% end %>
	</div>

	<div class="middle">
		<%= link_to image_tag('/images/logo-leprod.jpg'), 'http://www.uenf.br/Uenf/Pages/CCT/Leprod/'%>
		
		<%= link_to image_tag('/images/logo-uenf.jpg'), 'http://www.uenf.br' %>
		
		<%= link_to image_tag('/images/logo-pmi.jpg'), 'http://www.pmirio.org.br/' %>
	</div>
	
	<br />
	<fieldset>
		<legend>Últimas Notícias</legend>
		<%= render :partial => 'noticias/noticia_home', 
						:collection => @noticias.map {|n| n.corpo = "#{n.corpo[0..250]}. . ."; n} %>
		
	</fieldset>
</div>

app/views/pages/noticia_template.html.erb
<div class="item">
	<div class="title"><small>12º EENGE</small> <span class="azul"><%= @titulo %></span></div>
	
	<div class="body">

		<% if @noticia %>
			<%= raw RedCloth.new(@noticia.corpo).to_html %>
			<% if current_user.try(:admin) %>			
			  <%= link_to "Editar informações", edit_noticia_path(@noticia) %>
			<% end %>
		<% else %>
			<% if current_user.try(:admin) %>
			  <%= link_to "Inserir informações", new_noticia_path(:secao => @secao) %>
			<% end %>
		<% end %>
		
		
	</div>
	

</div>

app/views/pages/pagamento.html.erb
<div class="item">
	<div class="title">
		Formas de Pagamento
	</div>
	
	<div class="body">
		<p><strong>PagSeguro</strong>: Para a sua segurança e conforto, contamos com o PagSeguro como forma de pagamento. Com ele você protege seus dados financeiros (não informa os seus dados para o vendedor), o pagamento é seguro (você tem 14 dias para bloquear o pagamento) e paga como quiser (boleto ou tranferência eletrônica). Para isso você precisará fazer um breve cadastro no PagSeguro, caso não o tenha é possível fazê-lo na hora da compra.</p>
		
		<div class="center">
			<%= pagseguro_form @pedido, :submit => "Pagar com PagSeguro", :email => current_user.email %>
		</div>
	</div>	
</div>

<div class="item">
	<div class="body">
		<p><strong>""OUTRAS FORMAS DE PAGAMENTO""</strong></p>
	</div>
</div>