config/routes.rb
Eenge::Application.routes.draw do
  
  resources :album_de_fotos
  
  resources :fotos
  
  devise_for :users

  resources :inscricaos, :only => [:new, :create, :update, :edit]
  
  resources :users do
    post 'confirmar', :on => :member
    post 'desfazer', :on => :member
  end
  
  resources :contatos, :only => [:new, :create]
  
  root :to => 'pages#home'
  
  match '/patrocinio', :to => 'pages#sponsors', :via => :get
  match '/sobre', :to => 'pages#sobre', :via => :get
  match '/programacao', :to => 'pages#programacao', :via => :get
  match '/usuario', :to => 'users#show', :via => :get
  match '/localizacao', :to => 'pages#localizacao', :via => :get
  match '/contato', :to => 'pages#contato', :via => :get
  match '/cronograma', :to => 'pages#cronograma', :via => :get
  match '/minicursos', :to => 'pages#minicursos', :via => :get
  match '/coquetel', :to => 'pages#coquetel', :via => :get
  match '/visitas_tecnicas', :to => 'pages#visitas_tecnicas', :via => :get
  match '/como_chegar', :to => 'pages#como_chegar', :via => :get
  match '/aonde_ficar', :to => 'pages#aonde_ficar', :via => :get
  match '/ficha_cadastral', :to => 'users#ficha', :via => :get
  match '/pagamento', :to => 'pages#pagamento', :via => :get
  match '/congresso_pmi', :to => 'pages#congresso_pmi', :via => :get
  match '/efetuado', :to => 'pages#efetuado'  
  
  namespace :user do
    root :to => 'users#show'
  end
  
  resources :noticias, :except => [:index]
  resources :patrocinadores
    

end

app/views/layouts/_footer.html.erb
<p>Desenvolvido por <strong>Augusto Zangrandi</strong><br />
	<%= link_to "@zangrandii", 'http://twitter.com/a_zangrandi'%></p>

app/views/layouts/_greeting.html.erb
Olá

app/views/layouts/_header.html.erb
<div id="banner"><%= link_to banner, root_path %></div>

<div id="nav">
	<ul>	
		<li class="home">
			<%= link_to "HOME", root_path %>
		</li>
		
		<% if current_user.try(:admin) %>
			<li><%= link_to "INSCRIÇÃO", '#' %></li>
		<% elsif user_signed_in? %>
			<li><%= link_to "INSCRIÇÃO", usuario_path %></li>		
		<% else %>
			<li><%= link_to "INSCRIÇÃO", new_user_registration_path %></li>  
		<% end %>			

		<li>
			<%= link_to "O EENGE", sobre_path %>
		</li>

		<li>
			<%= link_to "CONGRESSO PMI RIO", congresso_pmi_path %>
		</li>
		
		<li>
			<%= link_to "PROGRAMAÇÃO", '#' %>
			<ul>
				<li><%= link_to "Cronograma", cronograma_path %></li>
				<li><%= link_to "Minicursos", minicursos_path %></li>
				<li><%= link_to "Visitas Técnicas", visitas_tecnicas_path %></li>
				<li><%= link_to "Coquetel", coquetel_path %></li>
			</ul>
		</li>
		
		<li>
			<%= link_to "LOCALIZAÇÃO", como_chegar_path %>
			<ul>
				<li><%= link_to "Como Chegar", como_chegar_path %></li>
				<li><%= link_to "Onde Ficar", aonde_ficar_path %></li>
			</ul>
		</li>			
		<li><%= link_to "CONTATO", new_contato_path %>
	</ul>
</div>

app/views/layouts/_main-footer.html.erb
<div id="realizacao">
	<h3>Realização</h3>
	
	<%= image_tag('/images/logo-comissao.jpg')%>
</div>

<div id="apoio">
	<h3>Apoio</h3>
	
		<%= link_to image_tag('/images/logo-uenf2.jpg'), 'http://www.uenf.br/'%>

		<%= link_to image_tag('/images/logo-faperj.jpg'), 'http://www.faperj.br/' %>

		<%= link_to image_tag('/images/logo-iff.gif'), 'http://www.iff.edu.br/' %>
		
		<%= link_to image_tag("/images/logo-IEG.jpg"), 'http://www.institutodegestao.com.br/' %>
		
		<%= link_to image_tag("/images/logo-mpm2.jpg"), 'http://www.mundopm.com.br/' %>

		<%= link_to image_tag("/images/logo-ururau.jpg", :size => '30x90'), 'http://www.ururau.com.br/' %>	

		<%= link_to image_tag("/images/logo-blow.jpg"), 'http://blowcosmeticos.com/' %>				
				
		<%= link_to image_tag("/images/logo-ternium.gif"), 'http://www.terniumbrasil.com/' %>		
</div>

app/views/layouts/_sidebar.html.erb
<%= render_cell :patrocinadores, :show, :user => current_user %>

app/views/layouts/_social.html.erb
<div class="item">
	<div class="login">
		<% if user_signed_in? %>
			<% if current_user.try(:admin) %>
				<li><strong><%= link_to "Gerenciar Inscritos", users_path %></strong></li>			
				<li><%= link_to "Nova Notícia", new_noticia_path %></li>
				<li><%= link_to "Novo Patrocinador", new_patrocinador_path %></li>
				<li><%= link_to "Editar data Inscrição", new_inscricao_path %></li>
				<li><%= link_to "Editar Minicursos", minicursos_path %>
				<li><%= link_to "Editar Email/Senha", edit_registration_path(current_user) %></li> <br />				
				<li><%= button_to "Sair", destroy_user_session_path, :method => "get" %></li>
			<% else %>
				<h5>Olá, <%= current_user.primeiro_nome %>!</h5>
				<li><%= link_to "Ver Inscrição", usuario_path %></li>
				<li><%= link_to "Editar Dados", edit_registration_path(current_user) %></li> <br />				
				<%= button_to "Sair", destroy_user_session_path, :method => "get" %>
			<% end %>
		<% else %>
			<h5>LOGIN</h5>
			<%= form_for("user", :url => user_session_path) do |f| %>
			  <p><%= f.label :email, "email" %><br />
			  <%= f.email_field :email, :size => 15 %></p>


				<!--[if IE]>
				  <p><%= f.label :password, "senha" %><br />
				  <%= f.password_field :password, :size => 16 %></p>
				<![endif]-->
				
				<!--[if !IE]><!-->
				<p><%= f.label :password, "senha" %><br />
			  <%= f.password_field :password, :size => 15 %></p>
				<!--<![endif]-->

			  <%= f.check_box :remember_me %> <%= f.label :remember_me, "Lembrar" %>
			
			  <p><%= f.submit "Login" %></p>
				<%= link_to "Esqueceu a senha?", new_password_path("user") %> <br /><br />
				<div class="button"><%= link_to "Faça sua inscrição", new_user_registration_path, :method => :get %></div>
			<% end %>
		<% end %>
	</div>
	
	<div class="login">
		<h5>PROGRAMAÇÃO</h5>
		<%= link_to image_tag("http://img511.imageshack.us/img511/1752/cronograma.png"), "http://img511.imageshack.us/img511/1752/cronograma.png" %>
	</div>
	
	<div class="fb">
		<%= link_to image_tag('/images/facebook.png', :size => '30x30'), 
					'https://www.facebook.com/profile.php?id=100002388831542', :class => "patrocinador" %>
		<%= link_to image_tag('/images/twitter.png', :size => '30x30'), 
					'http://twitter.com/12eengeproducao', :class => "patrocinador" %>
		<%= link_to image_tag('/images/orkut.jpg', :size => '30x30'),
					'http://www.orkut.com.br/Main#Profile?uid=14833616517075484044', :class => "patrocinador" %>				
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'custom' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'slides.min.jquery' %>
  <%= csrf_meta_tag %>

	<script type="text/javascript">
		var timeout         = 500;
		var closetimer		= 0;
		var ddmenuitem      = 0;

		function jsddm_open()
		{	jsddm_canceltimer();
			jsddm_close();
			ddmenuitem = $(this).find('ul').eq(0).css('visibility', 'visible');}

		function jsddm_close()
		{	if(ddmenuitem) ddmenuitem.css('visibility', 'hidden');}

		function jsddm_timer()
		{	closetimer = window.setTimeout(jsddm_close, timeout);}

		function jsddm_canceltimer()
		{	if(closetimer)
			{	window.clearTimeout(closetimer);
				closetimer = null;}}

		$(document).ready(function()
		{	
			$('#nav > li').bind('mouseover', jsddm_open);
			$('#nav > li').bind('mouseout',  jsddm_timer);
		
		});

	</script>
	
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) {return;}
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
   <%= yield :script %>
</head>

<body>
	<div id="content">		
	   <div id="header">
   		<%= render 'layouts/header' %>
   	</div>
		
		<div id="main">
			<div id="left-bar">
				<%= render 'layouts/social' %>
			</div>
			
			<div id="section">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, :class => "note") if value.length > 0 %>
				<% end %>	

				<%= yield %>
				
				<div id="facebook">
   				<div class="fb-like" data-href="http://www.eenge.com.br/producao" data-send="false" data-width="500" data-show-faces="true" data-colorscheme="light"></div>
				</div>
			</div>
			
			<div id="right-bar">
				<%= render 'layouts/sidebar' %>		
			</div>
			

		</div>
		
		<div id="bottom">
   		<%= render 'layouts/main-footer'%>		
		</div>
   		
      <div class="clear"></div>

	</div>
	
	<div id="footer">
	   <%= render 'layouts/footer' %>
   </div>
</body>
</html>

app/views/layouts/ficha.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery.twitter' %>
	<script src="http://widgets.twimg.com/j/2/widget.js"></script>	
  <%= csrf_meta_tag %>
	<link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
	
	<style type="text/css">
		#ficha_cadastral { 			font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;    
		 width: 800px; 
		                   border: 1px solid black ; margin: 0 20px; padding: 15px;}
		#ficha_cadastral table tr { width: 50%;}
		#ficha_cadastral table tr.space { height: 15px; }
		#ficha_cadastral table tr span { font-weight: bold; }
		#ficha_cadastral table tr td { width: 50%;}
		#ficha_cadastral table tr td.space { height: 15px; }
		#ficha_cadastral table tr td.subtitulo { border: 1px solid #a0a0a0; font-weight: bold; font-size: 110%; }
	</style>
</head>

<body>

	<%= yield %>
	
	<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/layouts/foto.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery.twitter' %>
  <%= javascript_include_tag 'slides.min.jquery' %>

	<script src="http://widgets.twimg.com/j/2/widget.js"></script>	
  <%= csrf_meta_tag %>
	<link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic:400,700' rel='stylesheet' type='text/css'>
	<script type="text/javascript">
		var timeout         = 500;
		var closetimer		= 0;
		var ddmenuitem      = 0;

		function jsddm_open()
		{	jsddm_canceltimer();
			jsddm_close();
			ddmenuitem = $(this).find('ul').eq(0).css('visibility', 'visible');}

		function jsddm_close()
		{	if(ddmenuitem) ddmenuitem.css('visibility', 'hidden');}

		function jsddm_timer()
		{	closetimer = window.setTimeout(jsddm_close, timeout);}

		function jsddm_canceltimer()
		{	if(closetimer)
			{	window.clearTimeout(closetimer);
				closetimer = null;}}

		$(document).ready(function()
		{	
			$('#nav > li').bind('mouseover', jsddm_open);
			$('#nav > li').bind('mouseout',  jsddm_timer);
			
			
			
		    $("#twitter").getTwitter({
		        userName: "Zangrandii",
		        numTweets: 8,
		        loaderText: "Carregando tweets...",
		        slideIn: true,
		        showHeading: true,
		        headingText: "Tweets",
		        showProfileLink: true
		    });
		});

	</script>
 <%= yield :script %>
</head>

<body>

	<div id="conteudo">
		<%= render 'layouts/header' %>
		
		<div id="section_wrapper">
			<div id="main">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, :class => "note") %>
				<% end %>	
			<!-- <p class="notice"><%= notice %></p>
		   <p class="alert"><%= alert %></p> -->
				<%= yield %>
			</div>
			
		</div>

		

	</div>
		<%= render 'layouts/footer'%>	
	<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'custom' %>
  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery.corner' %>
  <%= javascript_include_tag 'slides.min.jquery' %>
  <%= csrf_meta_tag %>

	<style>
		#main { width: 78%; }
		#main .item .body { overflow: scroll; }
	</style>
	<script type="text/javascript">
		var timeout         = 500;
		var closetimer		= 0;
		var ddmenuitem      = 0;

		function jsddm_open()
		{	jsddm_canceltimer();
			jsddm_close();
			ddmenuitem = $(this).find('ul').eq(0).css('visibility', 'visible');}

		function jsddm_close()
		{	if(ddmenuitem) ddmenuitem.css('visibility', 'hidden');}

		function jsddm_timer()
		{	closetimer = window.setTimeout(jsddm_close, timeout);}

		function jsddm_canceltimer()
		{	if(closetimer)
			{	window.clearTimeout(closetimer);
				closetimer = null;}}

		$(document).ready(function()
		{	
			$('#nav > li').bind('mouseover', jsddm_open);
			$('#nav > li').bind('mouseout',  jsddm_timer);
		
		});

	</script>
	
 <%= yield :script %>
</head>

<body>
	<div class="conteudo">		
		<%= render 'layouts/header' %>		
		<div id="section_wrapper">
			<div id="social">
				<%= render 'layouts/social' %>
			</div>
			<div id="main">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, :class => "note") if value.length > 0 %>
				<% end %>	
			<!-- <p class="notice"><%= notice %></p>
		   <p class="alert"><%= alert %></p> -->
				<%= yield %>
				<div class="facebook">
				<div id="fb-root"></div>
				<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) {return;}
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>

				<div class="fb-like" data-href="http://www.eenge.com.br/producao" data-send="false" data-width="500" data-show-faces="true" data-colorscheme="light"></div>
				</div>
			</div>
			
					
		</div>

		<!-- <div id="curso">Engenharia de Produção UENF</div> -->
		
		<%= render 'layouts/main-footer'%>

		
		
	</div>
	
		<%= render 'layouts/footer'%>	
	<%= debug(params) if Rails.env.development? %>

</body>
</html>